name: Test with Clang 17

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 17

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Build project
        run: |
          mkdir build
          cmake -S . -B build -G Ninja \
          -DCMAKE_CXX_COMPILER=${{ env.LLVM_PATH }}/bin/clang++ \
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++ -lc++abi"
          ninja -C build

      - name: Run tests
        run: |
          cd build
          ./mdspan_formatter_test