name: Test with Clang 17

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Clang 17
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 17

      - name: configure
        run: |
          mkdir build
          cmake -S . -B build \
            -DCMAKE_C_COMPILER=${{ env.LLVM_PATH }}/bin/clang \
            -DCMAKE_CXX_COMPILER=${{ env.LLVM_PATH }}/bin/clang++ \
            -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -stdlib=libc++ -v" \
            -DCMAKE_EXE_LINKER_FLAGS="${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++ -lc++abi"

      - name: build
        run: |
          cmake --build build --config Release -j4

      - name: test
        run: |
          ctest --test-dir build/test --build-config Release